### ISSUE TITLE
Why is `hook_views_api` defined here for the `search_api_views` module?

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/search_api_solr#2]
I believe this `hook_views_api` implementation is triggering warnings in my logs:

 - https://github.com/backdrop-contrib/search_api_solr/blob/1.x-1.x/search_api_solr.module#L133-L143

Besides which, it seems to already be defined in the `search_api_views` module:

 - https://github.com/backdrop-contrib/search_api/blob/1.x-1.x/contrib/search_api_views/search_api_views.module#L8-L16

I think we can just take it out here, right?

**Comment by argiepiano** [comment]
The main issue in the [first hook implementation you list above](https://github.com/backdrop-contrib/search_api_solr/blob/1.x-1.x/search_api_solr.module#L133-L143), is that, if module `search_api_views` is not enabled, then this hook will return `NULL`. This was not an issue in PHP 7.3, but it will generate warnings in 7.4+

And as you said, this hook implementation is not needed here, since `search_api_views.module` already implements it.

**Comment by laryn** [comment]
@earlyburg I made a quick PR to remove this `hook_views_api` implementation. See if you agree.

**Comment by earlyburg** [comment]
Looks good to me @laryn.
I'll merge it as soon as I get to my office.
